export const config = {
  IS_MIN_DISPLAY: 450,
  IS_MIDDLE_DISPLAY: 900,
  IS_MOBILE_MENU_SIZE: 768,
  IS_COUNT_MAX_WIDTH: 12,
  IS_INCREASE_MAX_WIDTH: 3,
  IS_COUNT_MIDDLE_WIDTH: 8,
  IS_INCREASE_MIDDLE_WIDTH: 2,
  IS_COUNT_MIN_WIDTH: 5,
  IS_INCREASE_MIN_WIDTH: 2,
  IS_TIMEOUT: 180,
}